// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package sqlc

import (
	"time"
)

type Driver struct {
	ID           int32     `db:"id"`
	UserID       string    `db:"user_id"`
	PoliceNumber string    `db:"police_number"`
	VehicleModel string    `db:"vehicle_model"`
	VehicleType  string    `db:"vehicle_type"`
	Nik          string    `db:"nik"`
	Address      string    `db:"address"`
	IsSimActive  bool      `db:"is_sim_active"`
	IsStnkActive bool      `db:"is_stnk_active"`
	CreatedAt    time.Time `db:"created_at"`
	UpdatedAt    time.Time `db:"updated_at"`
}

type Order struct {
	ID             string    `db:"id"`
	UserID         string    `db:"user_id"`
	DriverID       int32     `db:"driver_id"`
	OrderInquiryID string    `db:"order_inquiry_id"`
	PaymentID      string    `db:"payment_id"`
	Status         string    `db:"status"`
	CreatedAt      time.Time `db:"created_at"`
	UpdatedAt      time.Time `db:"updated_at"`
}

type OrderInquiry struct {
	ID                 string    `db:"id"`
	UserID             string    `db:"user_id"`
	OriginLat          float64   `db:"origin_lat"`
	OriginLong         float64   `db:"origin_long"`
	OriginAddress      string    `db:"origin_address"`
	DestinationLat     float64   `db:"destination_lat"`
	DestinationLong    float64   `db:"destination_long"`
	DestinationAddress string    `db:"destination_address"`
	Price              int64     `db:"price"`
	Distance           int32     `db:"distance"`
	Duration           int32     `db:"duration"`
	Routes             string    `db:"routes"`
	CreatedAt          time.Time `db:"created_at"`
	UpdatedAt          time.Time `db:"updated_at"`
}

type Payment struct {
	ID        string    `db:"id"`
	Amount    float64   `db:"amount"`
	Method    string    `db:"method"`
	Status    string    `db:"status"`
	QrStr     string    `db:"qr_str"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

type User struct {
	ID          string    `db:"id"`
	Name        string    `db:"name"`
	Email       string    `db:"email"`
	PhoneNumber string    `db:"phone_number"`
	Nim         string    `db:"nim"`
	CreatedAt   time.Time `db:"created_at"`
	UpdatedAt   time.Time `db:"updated_at"`
}
