// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"context"
)

type Querier interface {
	CreateDriver(ctx context.Context, arg CreateDriverParams) (int32, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (string, error)
	CreateOrderInquiry(ctx context.Context, arg CreateOrderInquiryParams) (string, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (string, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (string, error)
	DeleteDriver(ctx context.Context, id int32) error
	DeleteOrderInquiry(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	GetDriver(ctx context.Context, id int32) (Driver, error)
	GetDriverByUserID(ctx context.Context, userID string) (Driver, error)
	GetOrder(ctx context.Context, id string) (GetOrderRow, error)
	GetOrderHistory(ctx context.Context, userID string) ([]GetOrderHistoryRow, error)
	GetOrderInquiry(ctx context.Context, id string) (GetOrderInquiryRow, error)
	GetPayment(ctx context.Context, id string) (GetPaymentRow, error)
	GetUser(ctx context.Context, id string) (User, error)
	ListDrivers(ctx context.Context) ([]Driver, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateDriver(ctx context.Context, arg UpdateDriverParams) (int32, error)
	UpdatePaymentStatusToPaid(ctx context.Context, arg UpdatePaymentStatusToPaidParams) (string, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (string, error)
}

var _ Querier = (*Queries)(nil)
